### NumPy
Lavora con array, vettori e matrici.

Se necessario la installiamo con pip install numpy. 


In [80]:
import numpy as np

Creo un primo array.

In [81]:
v1 = np.array([1,2,3,4,5,6,7,8,9])
v1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Creo una matrice

In [82]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Per esaminare la struttura dei dati di numpy e capire se è una matrice, una lsta  un array usiamo shape:

In [83]:
v1.shape

(9,)

In [84]:
m1.shape

(3, 3)

La proprietà shape si può usare per modificare la forma dei dati. Es. da una lista passo a una matrice. 

L'importante è che righe x colonne = numero elementi

In [85]:
v2 = np.array([1,2,3,4,5,6,7,8,9])
print("prima forma:", v2.shape)
v2.shape=(3,3)
print("dopo la trasformazione:", v2.shape)

prima forma: (9,)
dopo la trasformazione: (3, 3)


Leggo un singolo elemento:

In [86]:
print(v2[0,0])

1


modifico un elemento singolo

In [87]:
v2[0,0] = 99
print(v2)

[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]


Tutti gli elementi di una __lista np__ sono __sempre omogenei__ diversamente dalle liste in Python.

_dtype_ riporta il tipo di dati della lista.

In [88]:
v2.dtype

dtype('int64')

Provo a inserire un numero con virgola nell'array _v2_. Purtroppo il tipo è definito e non è possibile modificarlo. L'elemento inserito perde la virgola.

In [89]:
#non va?
v2[1,1] = 3.3
print(v2)
v2.dtype

[[99  2  3]
 [ 4  3  6]
 [ 7  8  9]]


dtype('int64')

Per modificare il tipo di dati creo un nuovo array passandogli l'array da copiare (v2) e il nuovo tip di dati.

In [90]:
y= np.array(v2, dtype=float)
y[1,1] = 3.5
print(y)
y.dtype

[[99.   2.   3. ]
 [ 4.   3.5  6. ]
 [ 7.   8.   9. ]]


dtype('float64')

_dtype_ si può usare per forzare il tipo di dato dell'array una volta che è stato definito.

In [91]:
a1 = np.array([1,2,3,4,5])
print("il tipo prima: ", a1.dtype)
a1.dtype = np.float64
print("il tipo dopo la modifica: ", a1.dtype)
print(a1)

il tipo prima:  int64
il tipo dopo la modifica:  float64
[4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323]


## tipi dato ##
numpy gestisce tanti tipi di dato: int8/16/32, uint8/16/32/64, intp (per indexing) uintp (per puntatori), float32/64, complex64/128

In [92]:
c1 = np.array([1+1j, 2+3j, 3-2j])
print(c1)
print("somma di complessi: ", (c1[0] + c1[1]))

[1.+1.j 2.+3.j 3.-2.j]
somma di complessi:  (3+4j)


## operazioni ##


In [93]:
a = np.array([25, 50, 75, 100])
b = np.array([12, 23, 34, 45])

print("a+b", a+b)
print("a-b", a-b)
print("a*b", a*b)
print("a * 0.5 (modifica tipo): ", (a*0.5))
print("confronto a > 60", (a>60))

a+b [ 37  73 109 145]
a-b [13 27 41 55]
a*b [ 300 1150 2550 4500]
a * 0.5 (modifica tipo):  [12.5 25.  37.5 50. ]
confronto a > 60 [False False  True  True]


## generare array ##


In [94]:
v = np.arange(1,10)
print(v, v.shape)

[1 2 3 4 5 6 7 8 9] (9,)


In [95]:
v = np.arange(1,10).reshape(3,3)
print(v, v.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


valori casuali

In [96]:
m = np.random.random((4,4))
print(m)

[[0.37673101 0.31616111 0.61979665 0.03844116]
 [0.84923587 0.23477565 0.39698753 0.43218663]
 [0.51771162 0.55368129 0.30222922 0.54691117]
 [0.88038725 0.35744816 0.00380098 0.4318258 ]]


sono tutti numeri tra 0 e 1. 

In [97]:
m2 = m*100
print(m2)

[[37.67310095 31.6161108  61.97966521  3.84411621]
 [84.92358685 23.47756544 39.69875332 43.21866324]
 [51.77116182 55.36812905 30.22292159 54.69111661]
 [88.03872534 35.74481578  0.38009838 43.18258034]]


Per un array di numeri interi

In [99]:
m3 = np.random.randint(0, 100, (4, 4))
print(m3)

[[69 85 60 25]
 [70 21 19 58]
 [68 89 79 82]
 [27 42 30 55]]
