### NumPy
Lavora con array, vettori e matrici.

Se necessario la installiamo con pip install numpy. 


In [1]:
import numpy as np

Creo un primo array.

In [2]:
v1 = np.array([1,2,3,4,5,6,7,8,9])
v1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Creo una matrice

In [3]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Per esaminare la struttura dei dati di numpy e capire se è una matrice, una lsta  un array usiamo shape:

In [4]:
v1.shape

(9,)

In [5]:
m1.shape

(3, 3)

La proprietà shape si può usare per modificare la forma dei dati. Es. da una lista passo a una matrice. 

L'importante è che righe x colonne = numero elementi

In [6]:
v2 = np.array([1,2,3,4,5,6,7,8,9])
print("prima forma:", v2.shape)
v2.shape=(3,3)
print("dopo la trasformazione:", v2.shape)

prima forma: (9,)
dopo la trasformazione: (3, 3)


## Accesso ai valori
Leggo un singolo elemento:

In [7]:
print(v2[0,0])

1


modifico un elemento singolo

In [8]:
v2[0,0] = 99
print(v2)

[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]


Gli indici funzionano come per le liste python (split, negativi...)

In [26]:
n = np.array([0,1,2,3,4,5,6,7,8,9])
print(n[2])
print("negativo",n[-1])
print("range",n[3:5])
print("da 5 a fine",n[5:])
print("da inizio a 5",n[:5])

2
negativo 9
range [3 4]
da 5 a fine [5 6 7 8 9]
da inizio a 5 [0 1 2 3 4]


Con matrici a 2 e più dimensioni...
Cos'è una matrice?

In [29]:
n = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print("matrice:", n)
print("el:", n[1][2])


matrice: [[1 2 3]
 [4 5 6]
 [7 8 9]]
el: 6


riga

In [31]:
print(n[1])

[4 5 6]


colonna

In [32]:
print(n[:,0]) #tutti gli elementi in riga con indice di colonna 0

[1 4 7]


sottomatrici

In [39]:
print(n[1:3, 1:3])

[[5 6]
 [8 9]]


funzioni di modifica per array: insert e append. Attenzione che non modificano l'oggetto originale

In [42]:
n = np.array([1,2,3,4,5])
n2 = np.append(n, 100)
print("append", n, n2)

n3 = np.insert(n, 3, 100)
print("insert", n, n3)


append [1 2 3 4 5] [  1   2   3   4   5 100]
insert [1 2 3 4 5] [  1   2   3 100   4   5]


Tutti gli elementi di una __lista np__ sono __sempre omogenei__ diversamente dalle liste in Python.

_dtype_ riporta il tipo di dati della lista.

In [9]:
v2.dtype

dtype('int64')

Provo a inserire un numero con virgola nell'array _v2_. Purtroppo il tipo è definito e non è possibile modificarlo. L'elemento inserito perde la virgola.

In [10]:
#non va?
v2[1,1] = 3.3
print(v2)
v2.dtype

[[99  2  3]
 [ 4  3  6]
 [ 7  8  9]]


dtype('int64')

Per modificare il tipo di dati creo un nuovo array passandogli l'array da copiare (v2) e il nuovo tip di dati.

In [11]:
y= np.array(v2, dtype=float)
y[1,1] = 3.5
print(y)
y.dtype

[[99.   2.   3. ]
 [ 4.   3.5  6. ]
 [ 7.   8.   9. ]]


dtype('float64')

_dtype_ si può usare per forzare il tipo di dato dell'array una volta che è stato definito.

In [12]:
a1 = np.array([1,2,3,4,5])
print("il tipo prima: ", a1.dtype)
a1.dtype = np.float64
print("il tipo dopo la modifica: ", a1.dtype)
print(a1)

il tipo prima:  int64
il tipo dopo la modifica:  float64
[4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323]


## tipi dato ##
numpy gestisce tanti tipi di dato: int8/16/32, uint8/16/32/64, intp (per indexing) uintp (per puntatori), float32/64, complex64/128

In [13]:
c1 = np.array([1+1j, 2+3j, 3-2j])
print(c1)
print("somma di complessi: ", (c1[0] + c1[1]))

[1.+1.j 2.+3.j 3.-2.j]
somma di complessi:  (3+4j)


## operazioni ##


In [14]:
a = np.array([25, 50, 75, 100])
b = np.array([12, 23, 34, 45])

print("a+b", a+b)
print("a-b", a-b)
print("a*b", a*b)
print("a * 0.5 (modifica tipo): ", (a*0.5))
print("confronto a > 60", (a>60))

a+b [ 37  73 109 145]
a-b [13 27 41 55]
a*b [ 300 1150 2550 4500]
a * 0.5 (modifica tipo):  [12.5 25.  37.5 50. ]
confronto a > 60 [False False  True  True]


## generare array ##


In [15]:
v = np.arange(1,10)
print(v, v.shape)

[1 2 3 4 5 6 7 8 9] (9,)


In [16]:
v = np.arange(1,10).reshape(3,3)
print(v, v.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


valori casuali

In [17]:
m = np.random.random((4,4))
print(m)

[[0.98211627 0.18203163 0.28947357 0.93343116]
 [0.81996949 0.9408322  0.41553194 0.62745549]
 [0.13343735 0.1267061  0.82667695 0.28067419]
 [0.33620713 0.37946132 0.9829864  0.56943981]]


sono tutti numeri tra 0 e 1. 

In [18]:
m2 = m*100
print(m2)

[[98.21162742 18.20316267 28.94735681 93.34311555]
 [81.9969487  94.08321981 41.55319353 62.7455487 ]
 [13.34373502 12.67061014 82.66769517 28.06741932]
 [33.62071317 37.94613175 98.29863995 56.94398107]]


Per un array di numeri interi

In [19]:
m3 = np.random.randint(0, 100, (4, 4))
print(m3)

[[23 13 85 66]
 [95 34 28 75]
 [10 60 27 78]
 [44 27 19 17]]


Empty crea un array vuoto - !! o meglio non sappiamo cosa contenga!

In [20]:
m4 = np.empty((2, 2))
print(m4)

[[98.21162742 18.20316267 28.94735681 93.34311555]
 [81.9969487  94.08321981 41.55319353 62.7455487 ]
 [13.34373502 12.67061014 82.66769517 28.06741932]
 [33.62071317 37.94613175 98.29863995 56.94398107]]


Per un array con tutti 0, 1 o un valore a scelta si usano:

In [22]:
m5 = np.zeros((2, 2))
print(m5)
m5 = np.ones((2, 2))
print(m5)
m5 = np.full((2, 2), 3)
print(m5)
m5 = np.full((2, 2), True)
print(m5)
m5 = np.full((2, 2), 'a')
print(m5)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[3 3]
 [3 3]]
[[ True  True]
 [ True  True]]
[['a' 'a']
 ['a' 'a']]
