## filtri valori numpy


In [1]:
import numpy as np

In [4]:
n = np.random.randint(0,100, 10)
print(n)

n2 = np.arange(0,10)
print(n2)
np.random.shuffle(n2)
print(n2)

[90 90 66 41 35 87 26  2 43 47]
[0 1 2 3 4 5 6 7 8 9]
[0 3 2 4 9 1 5 7 8 6]


In [5]:
nf = n[n < 50]
print(nf)

[41 35 26  2 43 47]


In [6]:
nf = n[n == 41]
print(nf)

[41]


In [7]:
nf = n[n != 41]
print(nf)

[90 90 66 35 87 26  2 43 47]


In [8]:
nf = n[n >= 66]
print(nf)

[90 90 66 87]


In [9]:
nf = n[n%2 == 0]
print(nf)

[90 90 66 26  2]


In [10]:
nf = n[(n > 33) & (n < 60)]
print(nf)

[41 35 43 47]


In [11]:
nf = n[(n <= 33) | (n >= 60)]
print(nf)

[90 90 66 87 26  2]


In [12]:
nn = np.where((n%2 == 0), "P" , "D")
print(nn)

['P' 'P' 'P' 'D' 'D' 'D' 'P' 'P' 'D' 'D']


In [13]:
nn = np.where((n%2 == 0))
print(nn)

(array([0, 1, 2, 6, 7]),)


## arrotondamenti

In [14]:
v = np.random.random(10)
v *= 10.0
print(v)

[4.59161264 4.02529983 7.26853428 0.21511993 8.03159402 8.50853154
 4.07799124 6.73354302 3.0776603  5.9530251 ]


In [15]:
np.around(v, 2)

array([4.59, 4.03, 7.27, 0.22, 8.03, 8.51, 4.08, 6.73, 3.08, 5.95])

In [16]:
np.ceil(v)

array([5., 5., 8., 1., 9., 9., 5., 7., 4., 6.])

In [17]:
np.floor(v)

array([4., 4., 7., 0., 8., 8., 4., 6., 3., 5.])