## filtri e file

genero array casuale e poi lo filtro

In [2]:
import numpy as np
n = np.random.randint(0,100, 10)
print(n)

#alternativa con shuffle
from random import shuffle
n2 = np.arange(0,10)
np.random.shuffle(n2)
print(n2)

[58 34 65 28 84 67 46 20 66 18]
[5 7 4 1 8 3 9 0 6 2]


filtri

In [3]:
nf = n[n < 50]
print(nf)

[34 28 46 20 18]


In [4]:
nf = n[n == 50]
print(nf)

nf = n[n != 50]
print(nf)

nf = n[n >= 75]
print(nf)

[]
[58 34 65 28 84 67 46 20 66 18]
[84]


posso selezionare anche i pari!

In [5]:
nf = n[n%2 == 0]
print(nf)

[58 34 28 84 46 20 66 18]


posso comporre filtri con operatori and e or

In [6]:
nf = n[(n > 25) & (n < 75) ]
print(nf)

nf = n[(n < 25) | (n > 75) ]
print(nf)


[58 34 65 28 67 46 66]
[84 20 18]


In [7]:
nn = np.where((n%2 == 0), "P", "D")
print(nn)

['P' 'P' 'D' 'P' 'P' 'D' 'P' 'P' 'P' 'P']


Se non passo i valori da sostituire ottengo una lista con le posizioni dei valori.

In [8]:
nn = np.where((n%2 == 0))
print(nn)

(array([0, 1, 3, 4, 6, 7, 8, 9]),)


## Arrotondamenti


In [12]:
v = np.random.random(10)
v *= 10.0
print(v)

[6.89093784 6.33608218 9.69981889 9.36991825 3.79062994 7.48448878
 5.70991198 2.53591507 5.66960681 3.45109158]


In [13]:
np.around(v, 2)

array([6.89, 6.34, 9.7 , 9.37, 3.79, 7.48, 5.71, 2.54, 5.67, 3.45])

In [14]:
np.ceil(v)

array([ 7.,  7., 10., 10.,  4.,  8.,  6.,  3.,  6.,  4.])

In [15]:
np.floor(v)

array([6., 6., 9., 9., 3., 7., 5., 2., 5., 3.])