## Esercizio Lotteria
ispirato dal libro: DataScience con Python di Giuseppe Maggi - LSWR

Genero una lista di 90 numeri

In [1]:
import numpy as np

numeri = np.arange(1, 91)
print(numeri)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90]


posso mescolare la lista con shuffle(). 
es:


In [2]:
np.random.shuffle(numeri)
print(numeri)

[19 59 32 10 22 31 21 38 48 57  2 45 51 83 87 73 28 75  4 17 72 44 58 46
 26 25 71 13 67 34 43 52 20 84 40  9 85 80  1 11 42 39 37 41 53 88 36 77
 74  3 24  6 56 82 62 66 79 35 14 90 68 61 16 18 89 30  5 81 64  7 33 76
 49 65 70 54  8 63 60 78 12 47 27 69 86 15 23 29 55 50]


Creo una lista numpy vuota, in cui mettere le estrazioni

In [11]:
estrazioni = np.array([])

In [12]:
for i in range(5):
    #mescolo i numeri
    np.random.shuffle(numeri)
    estratti = numeri[0:5]
    #print(estratti)

    estrazioni = np.append(estrazioni, [estratti])

estrazioni = estrazioni.reshape(5,5)
print(estrazioni)

[33 29 76 63 54]
[19 75 41 15 58]
[52 66 13 16 48]
[54 80 20  1 26]
[43 51 73 56 11]
[[33. 29. 76. 63. 54.]
 [19. 75. 41. 15. 58.]
 [52. 66. 13. 16. 48.]
 [54. 80. 20.  1. 26.]
 [43. 51. 73. 56. 11.]]


In [14]:
import pandas as pd

#creo un range di date a partire da una data e per 6 giorni
dates = pd.date_range("20240901", periods=5)
print(dates)

DatetimeIndex(['2024-09-01', '2024-09-02', '2024-09-03', '2024-09-04',
               '2024-09-05'],
              dtype='datetime64[ns]', freq='D')


In [19]:
#poi genero i dati
df = pd.DataFrame(data=estrazioni, index=dates)
df

0     1     2     3     4
2024-09-01  33.0  29.0  76.0  63.0  54.0
2024-09-02  19.0  75.0  41.0  15.0  58.0
2024-09-03  52.0  66.0  13.0  16.0  48.0
2024-09-04  54.0  80.0  20.0   1.0  26.0
2024-09-05  43.0  51.0  73.0  56.0  11.0

cerco i ritardatari - servono le frequenze di apparizione dei numeri

devo contare da quante estrazioni non appare. Coviene partire dal fondo del data frame

In [20]:
for i in range(len(df)-1, -1, -1):  # Da len(df)-1 (ultima riga) a 0 (prima riga)
    #prelevo la riga
    print(df.iloc[i])

0    43.0
1    51.0
2    73.0
3    56.0
4    11.0
Name: 2024-09-05 00:00:00, dtype: float64
0    54.0
1    80.0
2    20.0
3     1.0
4    26.0
Name: 2024-09-04 00:00:00, dtype: float64
0    52.0
1    66.0
2    13.0
3    16.0
4    48.0
Name: 2024-09-03 00:00:00, dtype: float64
0    19.0
1    75.0
2    41.0
3    15.0
4    58.0
Name: 2024-09-02 00:00:00, dtype: float64
0    33.0
1    29.0
2    76.0
3    63.0
4    54.0
Name: 2024-09-01 00:00:00, dtype: float64


serve un dizionario
per ogni numero della riga... se non è nel dizionario, lo aggiungo inserendo il numero di giorni (è l'indice della riga)

In [22]:
ritardatari={}
for i in range(len(df)-1, -1, -1):  # Da len(df)-1 (ultima riga) a 0 (prima riga)
    #prelevo la riga
    riga = df.iloc[i]
    for num in riga:
        #print(num, i)
        if num not in ritardatari:
            ritardatari[num] = i

In [31]:
df = pd.DataFrame(list(ritardatari.items()), columns=['Valore', 'Conteggio'])
df


Valore  Conteggio
0     43.0          4
1     51.0          4
2     73.0          4
3     56.0          4
4     11.0          4
5     54.0          3
6     80.0          3
7     20.0          3
8      1.0          3
9     26.0          3
10    52.0          2
11    66.0          2
12    13.0          2
13    16.0          2
14    48.0          2
15    19.0          1
16    75.0          1
17    41.0          1
18    15.0          1
19    58.0          1
20    33.0          0
21    29.0          0
22    76.0          0
23    63.0          0