## Numpy e files

In [2]:
import numpy as np
lista = np.genfromtxt('numeri.txt')
print(lista)

[32.54 78.91 15.03 99.99  4.27 65.82 21.16 87.35 50.    1.79]


In [3]:
lista.dtype

dtype('float64')

In [4]:
lista.size

10

In [5]:
print("min: ", np.amin(lista))
print("max: ", np.amax(lista))
print("avg: ", np.average(lista))
print("std: ", np.std(lista))

min:  1.79
max:  99.99
avg:  45.68599999999999
std:  34.01310371018793


In [6]:
lista2 = lista * 1.10
print(lista2)

[ 35.794  86.801  16.533 109.989   4.697  72.402  23.276  96.085  55.
   1.969]


In [7]:
lista2 = np.around(lista2, 2)
print(lista2)

[ 35.79  86.8   16.53 109.99   4.7   72.4   23.28  96.08  55.     1.97]


In [8]:
np.savetxt("numeri_mod.txt", lista2, fmt='%0.2f')

## csv

In [9]:
l3 = np.loadtxt('sequenza2.csv', delimiter=',', skiprows=0)
print(l3)

[[12.34 98.76]
 [56.78 34.56]
 [78.9  12.34]
 [34.56 98.76]
 [98.76 56.78]
 [12.34 78.9 ]
 [56.78 34.56]
 [78.9  98.76]
 [34.56 12.34]
 [98.76 56.78]
 [12.34 78.9 ]
 [56.78 34.56]
 [78.9  98.76]
 [34.56 12.34]
 [98.76 56.78]
 [12.34 78.9 ]
 [56.78 34.56]
 [78.9  98.76]
 [34.56 12.34]
 [98.76 56.78]]


## binari

In [11]:
lista = np.genfromtxt('numeri.txt')
print(lista)

np.save('listabinaria', lista)

[32.54 78.91 15.03 99.99  4.27 65.82 21.16 87.35 50.    1.79]


In [12]:
dati = np.load('listabinaria.npy')
print(dati)

[32.54 78.91 15.03 99.99  4.27 65.82 21.16 87.35 50.    1.79]
